import './globals.css'
import Head from 'next/head'

// Components
import NavBar from './components/NavBar.jsx'
import Footer from './components/Footer.jsx'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
      </Head>
      <NavBar />
        <main>{children}</main>
      <Footer />
    </>
  )
}
